[Server]
Listen = ":19098"
AppName = "fastgo"
Env = "TEST"
[Auth]
Enable = false
Secret = "7ec164764dacaea974eae08966deef87"
Skips = [
]
[Auth.Accounts]
#key = secret
e76cb1d7079fdaf49422fe711bfd98c6 = "e10adc3949ba59abbe56e057f20f883e"

[Database]
Enable = true
UserPassword = "root:123456"
DB = "we"
[Database.Write]
HostPort = "tcp(49.233.193.41:33061)"
[Database.Read]
HostPort = "tcp(49.233.193.41:33061)"
[Database.Conn]
MaxLifeTime = 7200
MaxIdle = 50
MaxOpen = 50

[Log]
FilePath = "./log"
FileName = "fastgo"

[UploadDir]
Dir = "./files"
Host = "http://127.0.0.1:19098/v1/assets/"

[Wechat]
ApiKey = "wx12580e7fcadd5e7d"
ApiSecret = "676efdf15192f6524b6bc8e17fdee24b"